Models/Publicacao.cs
using System;
using System.Collections.Generic;
using System.IO;
using Microsoft.AspNetCore.Http;

namespace G8InstaDev.Models
{
    public class Publicacao : InstaDevBase, IPublicacao
    {
        public int IdPublicacao { get; set; }
        public string Imagem { get; set; }
        public string Legenda { get; set; }
        public int IdUsuario { get; set; }

        public string FotoUsuario { get; set; }
        public string NomeCompleto { get; set; }
        
        
        public string NomeUsuario { get; set; }
        
        

        private const string PATH = "Database/Feed.csv";

        Usuario usuarioModel = new Usuario();

        public Publicacao()
        {
            CreateFolderAndFile(PATH);
        }

        public string Prepare(Publicacao p)
        {
            return $"{p.IdPublicacao};{p.Imagem};{p.Legenda};{p.IdUsuario}";
        }

        public int idPublicacao()
        {
            var publicacoes = ReadAll();

            if (publicacoes.Count == 0)
            {
                return 1;
            }

            var codigo = publicacoes[publicacoes.Count - 1].IdPublicacao;

            codigo++;

            return codigo;
        }
        public void Create(Publicacao p)
        {
            string[] linhas = { Prepare(p) };
            File.AppendAllLines(PATH, linhas);
        }

        public void Delete(int id)
        {
            List<string> linhas = ReadAllLinesCSV(PATH);
            linhas.RemoveAll(x => x.Split(";")[0] == id.ToString());
            RewriteCSV(PATH, linhas);
        }

        public void DeletarTodasPublicacoesUsuario(int id){
            List<string> linhas = ReadAllLinesCSV(PATH);
            linhas.RemoveAll(x => x.Split(";")[3] == id.ToString());
            RewriteCSV(PATH, linhas);
        }

        public List<Publicacao> ReadAll()
        {
            List<Publicacao> feeds = new List<Publicacao>();
            string[] linhas = File.ReadAllLines(PATH);

            foreach (var item in linhas)
            {
                string[] linha = item.Split(";");

                Publicacao publicacao = new Publicacao();
                publicacao.IdPublicacao = int.Parse(linha[0]);
                publicacao.Imagem = linha[1];
                publicacao.Legenda = linha[2];
                publicacao.IdUsuario = int.Parse(linha[3]);





                // List<String> csv = usuarioModel.BuscarUsuarioPorId(publicacao.IdUsuario);
                // var linhaBuscada =
                // csv.Find(
                //     x =>
                //     x.Split(";")[0] == linha[3]
                // );

                var usuarioBuscado = usuarioModel.BuscarUsuarioPorId(publicacao.IdUsuario);

                // var usuarioLinha = linhaBuscada.Split(";");
                publicacao.FotoUsuario = usuarioBuscado.Foto;
                publicacao.NomeUsuario = usuarioBuscado.NomeDoUsuario;
                publicacao.NomeCompleto = usuarioBuscado.NomeCompleto;

                feeds.Add(publicacao);
            }

            feeds.Reverse();

            return feeds;
        }

        public List<Publicacao> Read(int id)
        {
            List<Publicacao> pubs = ReadAll();

            pubs = pubs.FindAll(pub => pub.IdPublicacao == id);
            pubs.Reverse();

            return pubs;
        }


        public List<Publicacao> AcharPostsDoUsuario(int id)
        {
            List<Publicacao> publicacoes = new List<Publicacao>();

            Usuario usuarioModel = new Usuario();

            var usuarioLinha = usuarioModel.BuscarUsuarioPorId(id);
            
            List<string> linhas = new List<string>();
            linhas.AddRange(File.ReadAllLines(PATH));

            var linhasDoUsuario = linhas.FindAll(x => x.Split(";")[3] == id.ToString());

            foreach (var item in linhasDoUsuario)
            {
                string[] linha = item.Split(";");


                Publicacao publicacao = new Publicacao();
                publicacao.IdPublicacao = int.Parse(linha[0]);
                publicacao.Imagem = linha[1];
                publicacao.Legenda = linha[2];
                publicacao.IdUsuario = int.Parse(linha[3]);
                publicacao.FotoUsuario = usuarioLinha.Foto;
                publicacao.NomeUsuario = usuarioLinha.NomeDoUsuario;
                publicacao.NomeCompleto = usuarioLinha.NomeCompleto;

                publicacoes.Add(publicacao);
            }

            publicacoes.Reverse();

            return publicacoes;
        }

        public void Update(Publicacao p)
        {
            List<string> linhas = ReadAllLinesCSV(PATH);
            linhas.RemoveAll(x => x.Split(";")[0] == p.IdPublicacao.ToString());
            linhas.Add(Prepare(p));
            RewriteCSV(PATH, linhas);
        }

        public Usuario Buscar(int id)
        {
            List<String> csv = usuarioModel.ReadAllLinesCSV("Database/Usuario.csv");

            var linhaBuscada =
            csv.Find(
                x =>
                x.Split(";")[0] == id.ToString()
            );

            var usuarioLinha = linhaBuscada.Split(";");
            Usuario usuarioBuscado = new Usuario();
            usuarioBuscado.Foto = usuarioLinha[6].ToString();
            usuarioBuscado.NomeDoUsuario = usuarioLinha[3].ToString();
            return usuarioBuscado;
        }
    }
}

Controllers/PublicacaoController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using G8InstaDev.Models;
using System.IO;
using Microsoft.AspNetCore.Http;

namespace G8InstaDev.Controllers
{
    [Route("Feed")]
    public class PublicacaoController : Controller
    {
         Publicacao feedModel = new Publicacao();
    
        [Route("Listar")]
         public IActionResult Index()
         {
            Usuario usuario = new Usuario();
            ViewBag.usuario = usuario.BuscarUsuarioPorId(int.Parse(HttpContext.Session.GetString("_IdLogado")));
            ViewBag.Feeds = feedModel.ReadAll();
            return View();
         }

        [Route("Cadastrar")]
        public IActionResult Cadastrar(IFormCollection form)
        {
            Publicacao novoFeed = new Publicacao();
            novoFeed.IdPublicacao = feedModel.idPublicacao();

            if (form.Files.Count > 0)
            {
                var file = form.Files[0];
                var folder = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/img/Feed");

                if (!Directory.Exists(folder))
                {
                    Directory.CreateDirectory(folder);
                }

                var nomeFoto = Guid.NewGuid();

                var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/img/", folder, nomeFoto.ToString() + ".png");

                using (var stream = new FileStream(path, FileMode.Create))
                {
                    // Salvamos o arquivo no caminho especificado
                    file.CopyTo(stream);
                }

                novoFeed.Imagem = nomeFoto.ToString() + ".png";

            }
            else
            {

                novoFeed.Imagem = "padrao.png";
            }

            novoFeed.Legenda = form["Legenda"];
            novoFeed.IdUsuario = int.Parse(HttpContext.Session.GetString("_IdLogado"));
            feedModel.Create(novoFeed);
            ViewBag.Feeds = feedModel.ReadAll();
            return LocalRedirect("~/Feed/Listar");

        }

        [Route("{id}")]
        public  IActionResult Excluir (int id)
        {
            feedModel.Delete(id);
            ViewBag.Jogadores = feedModel.ReadAll();
            return LocalRedirect("~/Feed/Listar");
        }

    }
}

Views/Publicacao/Index.cshtml
@using G8InstaDev.Models
@{
    ViewData["Title"] = "Home Page";
}


<section class="storys content flex-bt-center">
    <div class="barra">
        <div class="fotoUM">
            <img src="../imgs/storys/vin-diesel 1.png" alt="foto do usuário" class="foto-story">
            <br>
            <img src="../imgs/storys/vin_diesel.png" alt="Nome do usuario" class="espacamento">
        </div>

        <div class="fotoDOIS">
            <img src="../imgs/storys/gabigordo 1.png" alt="foto do usuário" class="foto-story">
            <br>
            <img src="../imgs/storys/gabigordo.png" alt="Nome do usuario" class="espacamento">
        </div>

        <div class="fotoTRES">
            <img src="../imgs/storys/will-baiano 1.png" alt="foto do usuário" class="foto-story">
            <br>
            <img src="../imgs/storys/will_baiano.png" alt="Nome do usuario" class="espacamento">
        </div>

        <div class="fotoQUATRO">
            <img src="../imgs/storys/tony_stark 1.png" alt="foto do usuário" class="foto-story">
            <br>
            <img src="../imgs/storys/adriano_stark.png" alt="Nome do usuario" class="espacamento">
        </div>

        <div class="fotoCINCO">
            <img src="../imgs/storys/pele 1.png" alt="foto do usuário" class="foto-story">
            <br>
            <img src="../imgs/storys/king_pele.png" alt="Nome do usuario" class="espacamento">
        </div>

        <div class="fotoSEIS">
            <img src="../imgs/storys/samuel-rosa-bebê 1.png" alt="foto do usuário" class="foto-story">
            <br>
            <img src="../imgs/storys/samuel_rosa.png" alt="Nome do usuario" class="espacamento">
        </div>

        <div class="fotoSETE">
            <img src="../imgs/storys/chaves_metal 1.png" alt="foto do usuário" class="foto-story">
            <br>
            <img src="../imgs/storys/chaves_metal.png" alt="Nome do usuario" class="espacamento">
        </div>
    </div>
</section>


<div class="fotoUSUARIO">
     <a asp-controller="Perfil" asp-route-IdUsuario="0"><img src="../img/Editar/@ViewBag.usuario.Foto"
            alt="foto de perfil do usuario logado " class="descida imagem-de-perfil"></a>
    <p class="sobe">@ViewBag.usuario.NomeDoUsuario</p>
    <br>
    <p class="espacao"><b>@ViewBag.usuario.NomeCompleto</b></p>
</div>

<section class="postar flex-bt-center content">
    <div class="retangulo">
        <div class="imagem-postar">
            <img src="~/img/Editar/@ViewBag.Usuario.Foto" alt="foto de perfil do usuario" class="imagem-de-perfil-post">
            <img src="~/imgs/Postar/Postar.png" alt="texto Postar" class="espaco">


            <form method="POST" class="post" action='@Url.Action("Cadastrar")' enctype="multipart/form-data">

                <input type="text" placeholder="Digite a descrição da imagem..." class="descricaoImagem" name="Legenda">

                <label for="arquivo">Escolha a imagem</label>
                <input type="file" name="Imagem" id="arquivo" />

                <button class="btnpostar" type="submit"> Postar </button>
            </form>
        </div>
    </div>

</section>
@foreach (Publicacao feed in ViewBag.Feeds)
{
    <section class="postAdicionado flex-bt-center content">
        <div class="card">
            <div class="perfil">
                <a asp-controller="Perfil" asp-route-IdUsuario="@feed.IdUsuario"><img class="foto-perfil" src="~/img/Editar/@feed.FotoUsuario" alt="Foto de perfil do usuário" width="40px"></a>
                <a asp-area="Link para excluir uma publicacao" asp-controller="Publicacao" asp-action="Excluir"
                    asp-route-id="@feed.IdPublicacao"><img src="../imgs/lixo.png" alt="Lixeira" class="lixo"></a>
                <img src="/img/Feed/@feed.Imagem" alt="Imagem do post @feed.Legenda" width="700">
            </div>

            <div class="icones">
                <img id="imagem_curtida" src="../imgs/postAdicionado/Vector.png" alt="icone curtida">
                <img src="../imgs/postAdicionado/Vector (1).png" alt="icone comentario" class="comentario">
                <input type="text" placeholder="Comentar..." class="comentario">
            </div>
            <div class="comentario-adicionado">
                <p class="texto-comentario"><b> @feed.NomeUsuario </b>@feed.Legenda</p>
                <div class="flex-comentario">
                    <p class="nome"> fausto_silva </p>
                    <p class="espacamentoo"> Esse cara é fera bicho!!!</p>
                </div>

                <div class="flex-comentario">
                    <p class="nome"> yes_baby </p>
                    <p class="espacamentoo"> thank you</p>
                </div>

    </section>
    
}